### ISSUE TITLE
Funzioni ad-hoc

### ISSUE THREAD

**Issue by dario2994** [walypala23/grader-creator#2]
Rendere facile scrivere funzioni ad-hoc (nei vari linguaggi) da includere adeguatamente (come libreria nel caso di pascal).
Anche questo deve avere un'opzione da riga di comando oppure nel grader_description.txt.

**Comment by wil93** [comment]
Fixed in 02b473eff925fa69ab996f70f2844c9531bb7fdb..02d631596ae33b192a9f1b294e8120284d74a8ea
